include: package:lints/recommended.yaml

analyzer:
  errors:
    annotate_overrides: error
    fixme: warning
    hack: warning
    invalid_use_of_protected_member: error
    missing_enum_constant_in_switch: error
    todo: ignore
    unreachable_switch_case: error
    unrelated_type_equality_checks: error
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true