include: package:lints/recommended.yaml

analyzer:
  errors:
    annotate_overrides: error
    avoid_catching_errors: error
    avoid_returning_null_for_void: error
    body_might_complete_normally_nullable: error
    collection_methods_unrelated_type: error
    equal_elements_in_set: error
    equal_keys_in_map: error
    fixme: warning
    hack: warning
    inference_failure_on_untyped_parameter: error
    invalid_use_of_protected_member: error
    missing_enum_constant_in_switch: error
    must_be_immutable: error
    no_wildcard_variable_uses: error
    override_on_non_overriding_member: error
    sort_pub_dependencies: error
    todo: ignore
    unreachable_switch_case: error
    unrelated_type_equality_checks: error
    use_build_context_synchronously: error
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - avoid_catching_errors
    - sort_pub_dependencies
    - unawaited_futures