name: dartstronomy_gear
description: Dart library for controlling astronomy equipment.
version: 1.0.0
homepage: https://claudiu.mn
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  meta: ^1.12.0
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8